#! /bin/sh

set -e

cmd=$(basename "$0")

bailing()
{
    echo>&2 "$cmd: bailing, $*"
}

usage()
{
    echo "Usage: $cmd [--help] [--stdin] [--prerelease <tag>]" >&2
}

help()
{
    cat <<EOF
calver - generate a calendar version based on commit history

Usage:
  $cmd [options]

Options:
  --help              show this help
  --stdin             read commit list from stdin instead of asking 'git'
  --prerelease <tag>  generate a prerelease tag (lowercase letters only)
EOF
}

stdin=no
prerelease=""

while [ $# -gt 0 ]
do
    case "$1" in
        --stdin)
            stdin=yes
            ;;
        --prerelease)
            prerelease="$2"
            if [ -z "$prerelease" ]
            then
                bailing "missing argument for --prerelease"
                usage>&2
                exit 1
            fi
            shift
            ;;
        --help)
            help
            exit 0
            ;;
        *)
            bailing "unknown option: $1"
            usage>&2
            exit 1
            ;;
    esac
    shift
done

# we couldn't use set -u until we've parsed the options
set -u

# let's start with only allowing lowercase english letters,
# expanding later is easier than restricting later
if echo "$prerelease" | LC_ALL=C grep -q '[^a-z]'
then
    bailing "prerelease tag must be lowercase letters only"
    usage>&2
    exit 1
fi

if [ "$stdin" = yes ]
then
    if [ -t 0 ]
    then
        bailing "nothing to read on stdin"
        usage>&2
        exit 1
    fi
    commit_list=$(cat)
else
    commit_list=$(git log --date=short --format=%cd)
fi

if [ ! "$commit_list" = "$(echo "$commit_list" | sort -r)" ]
then
    # Making no assumptions about the order of the commit list for now
    # but I think they can be in any order...
    bailing "commit list is not in order"
    exit 1
fi

last_commit_date=$(echo "$commit_list" | head -n 1)
year=$(echo "$last_commit_date" | cut -d '-' -f 1)
month=$(echo "$last_commit_date" | cut -d '-' -f 2)
day=$(echo "$last_commit_date" | cut -d '-' -f 3)

major="$year"

month=$(echo "$month" | sed 's/^0*//')
day=$(echo "$day" | sed 's/^0*//')
minor=$((month * 100 + day))

patch=$(echo "$commit_list" | grep -c "^$last_commit_date")

case "$prerelease" in
    "")
        ;;
    *)
        # Using patch twice here might look weird, but it should make sense
        # since the first one does represent what will be the patch number for
        # release if cut now and the second one is the number of commits in
        # this (presumed) prerelease branch.
        prerelease="-$prerelease.$patch"
        ;;
esac

echo "$major.$minor.$patch$prerelease"
