on:
  push:
    branches-ignore:
      - main

jobs:
  prerelease:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: gh release create $(./calver --prerelease "$GITHUB_REF_NAME") ./calver --generate-notes --prerelease
        env:
          GH_TOKEN: ${{ github.token }}
