on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gh release create $(./calver) ./calver --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
